---
- hosts: host_1
  become: true
  tasks:
    - name: Login into registry Emergya
      docker_login:
        registry: docker-registry.emergya.com:443
        username: "{{ user }}"
        password: "{{ pass }}"
        reauthorize: yes
    - name: Create container DNS master
      docker_container:
        name: dns-master
        image: docker-registry.emergya.com:443/emergya/emergya-docker-bind9:latest
        hostname: "{{ name_docker }}"
        restart_policy: always
        state: started
        networks:
          - name: bridge
            ipv4_address: "{{ ip }}"
        ports:
          - "53:53/udp"
          - "53:53"
          - "2022:22"
        volumes:
          - "~/.ssh:/root/.ssh"