- name: Login into registry
  docker_login:
    registry: "{{ docker_registry_url }}"
    username: "{{ user }}"
    password: "{{ pass }}"
    reauthorize: yes

- name: Create container DNS master
  docker_container:
    name: "{{ name_container }}"
    image: "{{ docker_registry_url }}/{{ docker_image_name }}"
    hostname: "{{ name_docker }}"
    restart_policy: always
    state: started
    networks:
      - name: "{{ network }}"
        ipv4_address: "{{ ip }}"
    purge_networks: yes
    ports: "{{ ports }}"
    volumes:
      - "{{ ssh_pub_key }}:/home/developer/.ssh/authorized_keys"