- name: Login into registry
  docker_login:
    registry: "{{ docker_registry_url }}"
    username: "{{ user }}"
    password: "{{ pass }}"
    reauthorize: yes

- name: Create container DNS master
  docker_container:
    name: dns-master
    image: "{{ docker_registry_url }}/{{ docker_image_name }}"
    hostname: "{{ name_docker }}"
    restart_policy: always
    state: started
    networks:
      - name: "{{ network }}"
        ipv4_address: "{{ ip }}"
    purge_networks: yes
    ports:
      - "5353:53/udp"
      - "5353:53"
      - "2022:22"
    volumes:
      - "{{ ssh_pub_key }}:/root/.ssh/authorized_keys"