---
all:
  hosts:
    localserver:
      ansible_connection: local
    dns-poc3:
      ansible_host: 10.0.0.1
      ansible_user: root
    dns-server:
      ansible_host: 172.22.0.55
      ansible_user: root
    server-host:
      ansible_host: 172.22.0.1
      ansible_user: jpcarmona
